# Setup
title: Catriona Matthews
tagline: My Blog
description: Night Night Teddy lives here
url: https://getpoole.com
paginate: 1
baseurl: ""
permalink: pretty

author:
  name:           'Catriona Matthews'
  url:            https://twitter.com/catmatthe

paginate:         5

# Custom vars
version:          2.1.0

# # Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag